version: 0.1
phases:
  pre_build:
    commands:
      - echo prebuild first step CloudWatch Logs Created
      - echo Installing source NPM dependencies...
      - echo node -v
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - echo node -v
  post_build:
    commands:
      - echo Build completed on `date`
      - echo node -v
# Include only the files required for your application to  1run.
artifacts:
  files:
    - '**/*'
  base-directory: build_output
